[package]
name = "earth_satellite_state"
version = "0.1.1"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = "2.0.12"

[features]
default = []
serde = ["dep:serde", "nalgebra/serde", "nalgebra/serde-serialize"]